tasks:
- init: |
    (
      sudo apt -y install cmake
      
      # Install Catch2
      cd ..
      git clone https://github.com/catchorg/Catch2.git
      cd Catch2
      cmake -Bbuild -H. -DBUILD_TESTING=OFF
      sudo cmake --build build/ --target install
      cd ../AdventOfCode
      
      cmake -S. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      cmake --build build --target all 
    )
vscode:
  extensions:
    - twxs.cmake
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cmake-tools
    
